anchor_version = "0.19.0"

[programs.devnet]
wallet_nft_mint = "BfkwLq6tGq2CFw24kQJK5ZxZfBMTnv8a4vKQq76pEpRk"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "ts-mocha --debug -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/metadata.so"
